
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import java.lang.String;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Employee_section.java
 *
 * Created on Apr 21, 2013, 11:40:52 PM
 */
/**
 *
 * @author manish
 */


public class Employee_section extends javax.swing.JFrame {

    /** Creates new form Employee_section */
    public Employee_section() {
        initComponents();
        this.setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText(" salary ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("leaves_count");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("leaves");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("emp_details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int x;
    String tempid2=Employee_Login.tempusrname;
  
        String sal="SELECT salary from MESS_EMPLOYEE where id ='"+tempid2+"';";
                //+ "select * from mess_employee";
      try{
        Connection con1= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/project","root","snehil");
        Statement stmt=con1.createStatement();
        ResultSet rs = stmt.executeQuery(sal);
        while(rs.next()){
//x =  ((Number) rs.getObject(1)).intValue();
        String y = Integer.toString(rs.getInt(1));
    
        JOptionPane.showMessageDialog(this, "Salary : "+ y);
        }
        }catch (Exception e){
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
   
   /* else{
    String sal="SELECT m.salary from MESS_EMPLOYEE m where m.id ='"+tempid2+"';";
try{Connection con1= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/project","root","snehil");
    Statement stmt=con1.createStatement();
ResultSet rs = stmt.executeQuery(sal);
while(rs.next()){
//x =  ((Number) rs.getObject(1)).intValue();
    String y = Integer.toString(rs.getInt(1));
    
JOptionPane.showMessageDialog(this, "Salary : "+ y);
}
}catch (Exception e){
JOptionPane.showMessageDialog(this, e.getMessage());
}
    } */  
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int x;
    String tempid3=Employee_Login.tempusrname;
    
    String leaves="Select e.leaves_count from mess_employee e where e.id='"+tempid3+"';";
try{Connection con1= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/project","root","snehil");
    Statement stmt=con1.createStatement();
ResultSet rs = stmt.executeQuery(leaves);
while(rs.next()){
//x =  ((Number) rs.getObject(1)).intValue();
    String y = Integer.toString(rs.getInt(1));
    
JOptionPane.showMessageDialog(this, "leaves taken: "+ y);
}
}catch (Exception e){
JOptionPane.showMessageDialog(this, e.getMessage());
}
    
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String tempid1=Employee_Login.tempusrname;
        String leaves_details="Select * from leaves l where l.id ='"+tempid1+"';";
        jTable1.setVisible(true);       
       try{
        //Class.forName("java.sql.driver");
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root","snehil");
         Statement stmt = con.createStatement();
         ResultSet rs = stmt.executeQuery(leaves_details);
         ResultSetMetaData md = rs.getMetaData();
         int columnCount = md.getColumnCount();
         Vector data=new Vector();
         Vector columnNames= new Vector();
         Vector row = new Vector(columnCount);

         for(int i=1;i<=columnCount;i++){
             columnNames.addElement(md.getColumnName(i));
            }
         
         while(rs.next()){
           for(int i=1; i<=columnCount; i++){
           row.addElement(rs.getObject(i));
          }      
          data.addElement(row);
        }
         
         DefaultTableModel model = new DefaultTableModel(data, columnNames);
    jTable1.setModel( model );

    rs.close();
    stmt.close();
    con.close();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String tempid=Employee_Login.tempusrname;
        String emp_details="Select p.name,e.* from mess_employee e,person p where e.id ='"+tempid+"' and p.id ='"+tempid+"';";
        
        jTable1.setVisible(true);
      //  DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    try{
        //Class.forName("java.sql.driver");
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root","snehil");
         Statement stmt = con.createStatement();
         ResultSet rs = stmt.executeQuery(emp_details);
         ResultSetMetaData md = rs.getMetaData();
         int columnCount = md.getColumnCount();
         //columnCount+=1;
         Vector data=new Vector();
         Vector columnNames= new Vector();
         Vector row = new Vector(columnCount);
         //columnNames.addElement("Name");
         for(int i=1;i<=columnCount;i++){
             columnNames.addElement(md.getColumnName(i));
 
            }
         
         //row.addElement(rs.getObject(columnCount+1));
         while(rs.next()){
           for(int i=1; i<=columnCount; i++){
           row.addElement(rs.getObject(i));
          }      
          data.addElement(row);
        }
         
         DefaultTableModel model = new DefaultTableModel(data, columnNames);
    jTable1.setModel( model );
 /*  while(rs.next()){
    String id=rs.getString(1);
    int sal = rs.getInt(2);
    int wrkhrs=rs.getInt(3);
    String empaddress=rs.getString(4);
    int yrjoined=rs.getInt(5);
    int leavcount=rs.getInt(6);   
    
    model.addRow(new Object[] {id});model.addRow(new Object[] {sal});
    model.addRow(new Object[] {wrkhrs});model.addRow(new Object[] {empaddress});
    model.addRow(new Object[] {yrjoined});model.addRow(new Object[] {leavcount});
    }
          
          */
    rs.close();
    stmt.close();
    con.close();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Employee_section().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables


}
