import com.mysql.jdbc.Connection;

import com.mysql.jdbc.ResultSetMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Student_section.java
 *
 * Created on Apr 21, 2013, 10:02:11 PM
 */
/**
 *
 * @author manish
 */
public class Student_section extends javax.swing.JFrame {

    /** Creates new form Student_section */
    
    public Student_section() {
        initComponents();
        this.setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText(" signed grubs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("mess bill");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("personal info");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("mess bill distribution");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-792)/2, (screenSize.height-376)/2, 792, 376);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String tempid=Student_Login.tempusrname;
        String emp_details="Select * from grubs g where g.id ='"+tempid+"';";
        
        jTable1.setVisible(true);
      //  DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    try{
        //Class.forName("java.sql.driver");
         Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/project", "root","snehil");
         Statement stmt = con.createStatement();
         ResultSet rs = stmt.executeQuery(emp_details);
         ResultSetMetaData md = (ResultSetMetaData) rs.getMetaData();
         int columnCount = md.getColumnCount();
         //columnCount+=1;
         Vector data=new Vector();
         Vector columnNames= new Vector();
         Vector row = new Vector(columnCount);
         //columnNames.addElement("Name");
         for(int i=1;i<=columnCount;i++){
             columnNames.addElement(md.getColumnName(i));
 
            }
         
         //row.addElement(rs.getObject(columnCount+1));
         while(rs.next()){
           for(int i=1; i<=columnCount; i++){
           row.addElement(rs.getObject(i));
          }      
          data.addElement(row);
        }
         
         DefaultTableModel model = new DefaultTableModel(data, columnNames);
    jTable1.setModel( model );
 
    rs.close();
    stmt.close();
    con.close();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String tempid=Student_Login.tempusrname;
    String total =" update total_bill set total_cost = mess_basic+price_total+grub_cost;"; 
String total_bill="Select * from total_bill t where  t.id='"+tempid+"';";
try{
        //Class.forName("java.sql.driver");
         Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/project", "root","snehil");
         Statement stmt = con.createStatement();
       //  ResultSet rs1=stmt.executeQuery(extra_price);
         
   stmt.executeUpdate(total);
        //stmt.executeUpdate(student_details3);
        ResultSet rs = stmt.executeQuery(total_bill);
         
         ResultSetMetaData md = (ResultSetMetaData) rs.getMetaData();
         int columnCount = md.getColumnCount();
         //columnCount+=1;
         Vector data=new Vector();
         Vector columnNames= new Vector();
         Vector row = new Vector(columnCount);
         //columnNames.addElement("Name");
         for(int i=1;i<=columnCount;i++){
             columnNames.addElement(md.getColumnName(i));
 
            }
         
         //row.addElement(rs.getObject(columnCount+1));
         while(rs.next()){
           for(int i=1; i<=columnCount; i++){
           row.addElement(rs.getObject(i));
          }      
          data.addElement(row);
        }
         
         DefaultTableModel model = new DefaultTableModel(data, columnNames);
    jTable1.setModel( model );
 /*  while(rs.next()){
    String id=rs.getString(1);
    int sal = rs.getInt(2);
    int wrkhrs=rs.getInt(3);
    String empaddress=rs.getString(4);
    int yrjoined=rs.getInt(5);
    int leavcount=rs.getInt(6);   
    
    model.addRow(new Object[] {id});model.addRow(new Object[] {sal});
    model.addRow(new Object[] {wrkhrs});model.addRow(new Object[] {empaddress});
    model.addRow(new Object[] {yrjoined});model.addRow(new Object[] {leavcount});
    }
          
          */
    rs.close();
    stmt.close();
    con.close();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }    
    
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
String tempid=Student_Login.tempusrname;
        String student_details2 = "update extras set price_total =  price * quantity ;";
     //   String extra_price = " select price_total from extras where extras.id='"+tempid+"';";
        
     //  String student_details3 = "update students set mess_bill = mess_bill ;" +extra_price;
        String student_details="Select p.name,e.* from students e,person p where e.id ='"+tempid+"' and p.id ='"+tempid+"';";
        jTable1.setVisible(true);
      //  DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    try{
        //Class.forName("java.sql.driver");
         Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/project", "root","snehil");
         Statement stmt = con.createStatement();
       //  ResultSet rs1=stmt.executeQuery(extra_price);
         
   stmt.executeUpdate(student_details2);
        //stmt.executeUpdate(student_details3);
         ResultSet rs = stmt.executeQuery(student_details);
         
         ResultSetMetaData md = (ResultSetMetaData) rs.getMetaData();
         int columnCount = md.getColumnCount();
         //columnCount+=1;
         Vector data=new Vector();
         Vector columnNames= new Vector();
         Vector row = new Vector(columnCount);
         //columnNames.addElement("Name");
         for(int i=1;i<=columnCount;i++){
             columnNames.addElement(md.getColumnName(i));
 
            }
         
         //row.addElement(rs.getObject(columnCount+1));
         while(rs.next()){
           for(int i=1; i<=columnCount; i++){
           row.addElement(rs.getObject(i));
          }      
          data.addElement(row);
        }
         
         DefaultTableModel model = new DefaultTableModel(data, columnNames);
    jTable1.setModel( model );
 /*  while(rs.next()){
    String id=rs.getString(1);
    int sal = rs.getInt(2);
    int wrkhrs=rs.getInt(3);
    String empaddress=rs.getString(4);
    int yrjoined=rs.getInt(5);
    int leavcount=rs.getInt(6);   
    
    model.addRow(new Object[] {id});model.addRow(new Object[] {sal});
    model.addRow(new Object[] {wrkhrs});model.addRow(new Object[] {empaddress});
    model.addRow(new Object[] {yrjoined});model.addRow(new Object[] {leavcount});
    }
          
          */
    rs.close();
    stmt.close();
    con.close();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }    
    
    
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 String query=" select * from students;" ;
 String tempid=Student_Login.tempusrname;
     jTable1.setVisible(true);
      //  DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    try{
        //Class.forName("java.sql.driver");
         Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/project", "root","snehil");
         Statement stmt = con.createStatement();
     // ResultSet rs2 = stmt.executeQuery(student_details2);
      //   ResultSet rs3 = stmt.executeQuery(student_details3);
        ResultSet rs = stmt.executeQuery(query);
         
         ResultSetMetaData md = (ResultSetMetaData) rs.getMetaData();
         int columnCount = md.getColumnCount();
         //columnCount+=1;
         Vector data=new Vector();
         Vector columnNames= new Vector();
         Vector row = new Vector(columnCount);
         //columnNames.addElement("Name");
         for(int i=1;i<=columnCount;i++){
             columnNames.addElement(md.getColumnName(i));
 
            }
         
         //row.addElement(rs.getObject(columnCount+1));
         while(rs.next()){
           for(int i=1; i<=columnCount; i++){
           row.addElement(rs.getObject(i));
          }      
          data.addElement(row);
        }
         
         DefaultTableModel model = new DefaultTableModel(data, columnNames);
    jTable1.setModel( model );
 /*  while(rs.next()){
    String id=rs.getString(1);
    int sal = rs.getInt(2);
    int wrkhrs=rs.getInt(3);
    String empaddress=rs.getString(4);
    int yrjoined=rs.getInt(5);
    int leavcount=rs.getInt(6);   
    
    model.addRow(new Object[] {id});model.addRow(new Object[] {sal});
    model.addRow(new Object[] {wrkhrs});model.addRow(new Object[] {empaddress});
    model.addRow(new Object[] {yrjoined});model.addRow(new Object[] {leavcount});
    }
          
          */
    rs.close();
    stmt.close();
    con.close();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }    
    // TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Student_section().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
